### PR TITLE
Issue #4: Fixed the pointer size to ensure proper memory access

### PR DESCRIPTION
**Pull request by agrueso**
This change tries to resolve the issue #4: An AccessViolationException is sent by the PropVariant class

### CODE REVIEW

**Comment by zeus82** [comment]
This fixed an issue we were having!

**Comment by BasPaap** [comment]
This fixed an extremely obscure and hard to debug problem for me as well. I have a web application that needs to retrieve file metadata via ShellObject.Properties.System.ItemAuthors.Value. This kept crashing the IIS process if files had a title or authors and such containing unicode characters like "þ". Oddly, it only crashed on that server, not when running locally, and it also worked fine if I just created a simple WPF app to read the metadata from those same files and ran it on the server. So the problem _only_ occurred when running on Windows Server 2012 R2, in an ASP.NET MVC application, when reading files with unicode characters in their metadata.

With no exceptions or crash data, I've been debugging the problem for days. Your fix cleared everything right up! Many thanks!

**Review by singularity15 — APPROVED** [review]
This also fixed an issue I was running into- let's get this into the next release.

**Comment by billybednar** [comment]
Can anyone explain why the offset of the `_ptr2` field should be 16 instead of 12? As far as I can tell from the [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380072(v=vs.85).aspx), the original is correct. Here's a condensed version of the structure definition. The `_ptr2` field is the data pointer for the blob and vector cases.

```
struct PROPVARIANT {
	VARTYPE  vt;                  // 2 bytes @ 0
	WORD     wReserved1;          // 2 bytes @ 2
	WORD     wReserved2;          // 2 bytes @ 4
	WORD     wReserved3;          // 2 bytes @ 6
	union {
		struct BLOB    blob {
			ULONG    cbSize;      // 4 bytes @ 8
			BYTE     *pBlobData;  // 4/8 bytes @ 12
		};
		struct CA<T>   ca<T> {
			ULONG  cElems;        // 4 bytes @ 8
			T      *pElems;       // 4/8 bytes @ 12
		};
	};
};
```

**Pull request closed without merging**
